### ISSUE TITLE
Creating the UI for frontend

### ISSUE THREAD

**Issue by parthpatil01** [devpatel43543/practice_gitBoard#1]
Description:
Develop the user interface for the frontend using modern frameworks and design principles. Ensure the UI is responsive, visually appealing, and user-friendly. Key components include navigation, layout, and basic interactivity.

Technologies: React, Tailwind CSS (or other CSS frameworks), JavaScript.
Milestones: Initial layout design, responsive adjustments, and implementation of core UI components.

Tasks:
Create basic layout structure (Header, Main Content, Footer).
Implement responsive design for mobile and desktop.
Style UI components using Tailwind CSS.
Assign interactivity for buttons, links, etc.

**Comment by devpatel43543** [comment]
okay parth so i have to design just login page or do i need to do signup page

**Comment by parthpatil01** [comment]
yeah go ahead do it both
